---
# Demo Ansible Requirements
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.crypto
    version: ">=2.10.0"

roles:
  - name: geerlingguy.security
    version: "2.0.1"
  - name: geerlingguy.firewall
    version: "2.4.0"